dist: xenial
language: python
python: 2.7

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-8

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y make gcc libaio-dev libblkid-dev

env:
    - CC="gcc-8"

script:
    - make BUILDARGS="--build-lib=."
    - source tests/env.sh
    - pytest
